In [1]:
import numpy

a = numpy.ones([4,4])
a += 4
print(a)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [2]:
a.shape = (2,8)
print(a)

[[5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5.]]
